### ISSUE TITLE
 ошибка при попытке деобфнуть

### ISSUE THREAD

**Issue by discoart** [untitled-1111/JitTools#2]
[Moonsec Dumper] [WinError 2] Не удается найти указанный файл
[!] В JitTools произошла ошибка, сообщите о ней автору!

**Comment by untitled-1111** [comment]
Здравствуйте, в течении 15 минут будет опубликована новая версия, где данная ошибка исправлена.
Если вы снова столкнетесь с проблемой, пересоздайте данную тему
