### ISSUE TITLE
зависла

### ISSUE THREAD

**Issue by discoart** [untitled-1111/JitTools#3]
10 минут уже жду, гуишка зависла (не отвечает)  при попытке снять защиту с мунсека. ошибок нет, в консоли только
[MOONSEC-DUMPER] HOOKS INSTALLED =)
![image](https://github.com/user-attachments/assets/f62434fb-2e88-4dae-9860-14e1e550efe6)

**Comment by untitled-1111** [comment]
скинь файл сюда

**Comment by discoart** [comment]
> скинь файл сюда

обфусцированный файл?

**Comment by untitled-1111** [comment]
> > скинь файл сюда
> 
> обфусцированный файл?

да, скинь файл, который пытаешься открыть

**Comment by discoart** [comment]
[onyxhub crack.txt](https://github.com/user-attachments/files/17791834/onyxhub.crack.txt)

**Comment by untitled-1111** [comment]
> [onyxhub crack.txt](https://github.com/user-attachments/files/17791834/onyxhub.crack.txt)

попробуй подождать в районе 5 минут, если проблема не исчезнет, придется изучать код через "Анализ > Просмотр инструкций"

**Comment by discoart** [comment]
> > [onyxhub crack.txt](https://github.com/user-attachments/files/17791834/onyxhub.crack.txt)
> 
> попробуй подождать в районе 5 минут, если проблема не исчезнет, придется изучать код через "Анализ > Просмотр инструкций"

проблема в скрипте или в мунсеке, на другом скрипте может сработать?

**Comment by untitled-1111** [comment]
> > > [onyxhub crack.txt](https://github.com/user-attachments/files/17791834/onyxhub.crack.txt)
> > 
> > 
> > попробуй подождать в районе 5 минут, если проблема не исчезнет, придется изучать код через "Анализ > Просмотр инструкций"
> 
> проблема в скрипте или в мунсеке, на другом скрипте может сработать?

проблема в скрипте
вероятнее всего:
1. слишком большой код, из-за этого долго обрабатывается
2. помимо обфускатора накинуты еще неизвестные опкоды, из-за них тоже может быть долгая обработка

на других скриптах все должно работать нормально, я тестировал мунсек

**Comment by discoart** [comment]
tools\Debugger\luajit.exe: C:\Users\╚трэ\Downloads\test m.lua:271: control structure too long near ';'

**Comment by discoart** [comment]
другой скрипт
пишет, что успешный дамп, сохранил его, но в консоли это (выше)

**Comment by discoart** [comment]
[test m.txt](https://github.com/user-attachments/files/17791881/test.m.txt)

**Comment by untitled-1111** [comment]
> tools\Debugger\luajit.exe: C:\Users\╚трэ\Downloads\test m.lua:271: control structure too long near ';'

либо ошибка в скрипте, либо я допустил ошибку в дампере, попробуй вручную убери ";" после использования функции moonsecdump, и запусти скрипт через tools/Debugger/luajit.exe

**Comment by untitled-1111** [comment]
перепроверю код и исправлю в ближайшую неделю

**Comment by untitled-1111** [comment]
у меня все работает, проблема на вашей стороне

**Comment by untitled-1111** [comment]
![image](https://github.com/user-attachments/assets/22251851-81b3-4ae0-99be-63bab442a644)

скрипт с ошибкой.
