### ISSUE TITLE
[BUG] Error при декомпиляции из-за названия

### ISSUE THREAD

**Issue by Alex-Adguard-Android** [untitled-1111/JitTools#5]
Не работает ни LJD ни PY декомпилятор из-за того что написал большую D а не d

LJD и PY

![image](https://github.com/user-attachments/assets/71299ae4-b507-4e9a-b2c5-5bd3d917cf9f)
Жду патча

**Comment by untitled-1111** [comment]
![image](https://github.com/user-attachments/assets/05e1c978-857b-451c-913d-fd4f1ca87df5)

**Comment by untitled-1111** [comment]
исправлено.
https://github.com/untitled-1111/JitTools/releases/download/1.8/Installer_JitTools_v1.8.zip
